version: "3"

networks:
  dcs:
    external: false

services:
  dcs:
    image: unfoldingword/dcs:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=dcs
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - dcs
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
 
  db:
    image: mysql:5
    platform: linux/intel
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=dcs
    networks:
      - dcs
    volumes:
      - ./mysql:/var/lib/mysql


